apiVersion: v1
kind: Pod
metadata:
   name: dynamic-agents
   labels:
      app: dynamic-agents
spec:
  containers:
  - name: maven
    image: maven:3.9.6-eclipse-temurin-17-focal
    command:
    - cat 
    tty: true
    volumeMounts: 
    - name: jenkins-agents-data 
      mountPath: /root/.m2
  - name: docker
    image: docker
    command:
    - cat
    tty: true
  volumes:
  - name: jenkins-agents-data
    persistentVolumeClaim:
        claimName: jenkins-agents